package GUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;

/**
 *
 * @author Arber
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CategoryBTN = new javax.swing.JButton();
        productsBTN = new javax.swing.JButton();
        ordersBTN = new javax.swing.JButton();
        LoguotBTN = new javax.swing.JButton();
        LoguotBTN1 = new javax.swing.JButton();
        ordersBTN1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CategoryBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CategoryBTN.setText("Category");
        CategoryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryBTNActionPerformed(evt);
            }
        });
        getContentPane().add(CategoryBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 187, 45));

        productsBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        productsBTN.setText("Products");
        productsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsBTNActionPerformed(evt);
            }
        });
        getContentPane().add(productsBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 187, 45));

        ordersBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ordersBTN.setText("Update Products");
        ordersBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ordersBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, 187, 45));

        LoguotBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoguotBTN.setText("Exit");
        LoguotBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoguotBTNActionPerformed(evt);
            }
        });
        getContentPane().add(LoguotBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 20, 75, 45));

        LoguotBTN1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoguotBTN1.setText("Logout");
        LoguotBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoguotBTN1ActionPerformed(evt);
            }
        });
        getContentPane().add(LoguotBTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 20, 80, 45));

        ordersBTN1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ordersBTN1.setText("Add Products");
        ordersBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersBTN1ActionPerformed(evt);
            }
        });
        getContentPane().add(ordersBTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 187, 44));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard-bg.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CategoryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryBTNActionPerformed
        new Category().setVisible(true); 
        this.dispose();     }//GEN-LAST:event_CategoryBTNActionPerformed

    private void LoguotBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoguotBTNActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you want to close it?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_LoguotBTNActionPerformed

    private void productsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsBTNActionPerformed
        new Products().setVisible(true);
    }//GEN-LAST:event_productsBTNActionPerformed

    private void ordersBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersBTNActionPerformed
       new Orders().setVisible(true);
    }//GEN-LAST:event_ordersBTNActionPerformed

    private void LoguotBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoguotBTN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoguotBTN1ActionPerformed

    private void ordersBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersBTN1ActionPerformed
        new AddProduct().setVisible(true);
    }//GEN-LAST:event_ordersBTN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CategoryBTN;
    private javax.swing.JButton LoguotBTN;
    private javax.swing.JButton LoguotBTN1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton ordersBTN;
    private javax.swing.JButton ordersBTN1;
    private javax.swing.JButton productsBTN;
    // End of variables declaration//GEN-END:variables
}
