/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import model.Product;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Arber
 */
public class Products extends javax.swing.JFrame {

    /**
     * Creates new form Products
     */
    public Products() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomeBTN = new javax.swing.JButton();
        AddProductsBTN = new javax.swing.JButton();
        CategoryBTN = new javax.swing.JButton();
        ordersBTN = new javax.swing.JButton();
        LoguotBTN = new javax.swing.JButton();
        ProductID = new javax.swing.JTextField();
        ProductName1 = new javax.swing.JTextField();
        Quantity1 = new javax.swing.JTextField();
        Price1 = new javax.swing.JTextField();
        Category1 = new javax.swing.JComboBox<>();
        PruductId = new javax.swing.JLabel();
        ProductName = new javax.swing.JLabel();
        Quantity = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        Category = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HomeBTN.setText("Home");
        HomeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBTNActionPerformed(evt);
            }
        });

        AddProductsBTN.setText("Add Products");
        AddProductsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductsBTNActionPerformed(evt);
            }
        });

        CategoryBTN.setText("Category");
        CategoryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryBTNActionPerformed(evt);
            }
        });

        ordersBTN.setText("Orders");
        ordersBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersBTNActionPerformed(evt);
            }
        });

        LoguotBTN.setText("Logout");
        LoguotBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoguotBTNActionPerformed(evt);
            }
        });

        ProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductIDActionPerformed(evt);
            }
        });

        ProductName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductName1ActionPerformed(evt);
            }
        });

        Category1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Category1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Category1ActionPerformed(evt);
            }
        });

        PruductId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PruductId.setText("Product ID");

        ProductName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ProductName.setText("Product Name");

        Quantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Quantity.setText("Quantity");

        Price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Price.setText("Price");

        Category.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Category.setText("Category");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(427, 427, 427)
                                .addComponent(CategoryBTN)
                                .addGap(32, 32, 32)
                                .addComponent(ordersBTN))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(253, 253, 253)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PruductId, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HomeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ProductName)
                                    .addComponent(Quantity)
                                    .addComponent(Price)
                                    .addComponent(Category))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ProductName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Quantity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Price1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Category1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(LoguotBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addComponent(AddProductsBTN)))
                .addContainerGap(334, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CategoryBTN, HomeBTN, LoguotBTN, ordersBTN});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AddProductsBTN, Category, Category1, Price, Price1, ProductID, ProductName, ProductName1, PruductId, Quantity, Quantity1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CategoryBTN)
                            .addComponent(LoguotBTN)
                            .addComponent(ordersBTN)
                            .addComponent(HomeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PruductId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductName))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quantity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quantity))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Price1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Price))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Category1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Category))
                .addGap(125, 125, 125)
                .addComponent(AddProductsBTN)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {CategoryBTN, HomeBTN, LoguotBTN, ordersBTN});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AddProductsBTN, Category, Category1, Price, Price1, ProductID, ProductName, ProductName1, PruductId, Quantity, Quantity1});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductIDActionPerformed
private void saveProductToFile(Product product) throws IOException {
    String filePath = "data/inventory.txt"; // File path
    try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath, true))) { // Append mode
        writer.write(product.toString());
        writer.newLine();
    }
}
private void clearForm() {
    ProductID.setText("");
    ProductName1.setText("");
    Price1.setText("");
    Quantity1.setText("");
    Category1.setSelectedIndex(0);
}

    private void AddProductsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductsBTNActionPerformed
String id = ProductID.getText();
    String name = ProductName1.getText();
    String category = (String) Category1.getSelectedItem();
    double price;
    int quantity;

    try {
        price = Double.parseDouble(Price1.getText());
        quantity = Integer.parseInt(Quantity1.getText());

        // Create a new product instance
        Product product = new Product(id, name, price, quantity, category);

        // Save product to file
        saveProductToFile(product);

        JOptionPane.showMessageDialog(this, "Product added successfully!");
        clearForm();

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid price or quantity!", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "Error saving product!", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_AddProductsBTNActionPerformed

    private void ProductName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductName1ActionPerformed

    private void Category1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Category1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Category1ActionPerformed

    private void HomeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBTNActionPerformed
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeBTNActionPerformed

    private void ordersBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersBTNActionPerformed
        new Orders().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ordersBTNActionPerformed

    private void CategoryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryBTNActionPerformed
        new Category().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CategoryBTNActionPerformed

    private void LoguotBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoguotBTNActionPerformed
       new Login().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_LoguotBTNActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProductsBTN;
    private javax.swing.JLabel Category;
    private javax.swing.JComboBox<String> Category1;
    private javax.swing.JButton CategoryBTN;
    private javax.swing.JButton HomeBTN;
    private javax.swing.JButton LoguotBTN;
    private javax.swing.JLabel Price;
    private javax.swing.JTextField Price1;
    private javax.swing.JTextField ProductID;
    private javax.swing.JLabel ProductName;
    private javax.swing.JTextField ProductName1;
    private javax.swing.JLabel PruductId;
    private javax.swing.JLabel Quantity;
    private javax.swing.JTextField Quantity1;
    private javax.swing.JButton ordersBTN;
    // End of variables declaration//GEN-END:variables
}
